-- V3__create_click_events.sql
-- Create click events table for analytics

CREATE TABLE click_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_link_id BIGINT NOT NULL,
  accessed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_click_events_short_link FOREIGN KEY (short_link_id) REFERENCES short_links(id) ON DELETE RESTRICT
);

CREATE INDEX ix_click_events_short_link_time ON click_events (short_link_id, accessed_at);
